# Generated by Django 5.1.11 on 2025-08-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="number",
            field=models.CharField(max_length=15),
        ),
    ]
